# Generated by Django 3.2.9 on 2022-02-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='item_name',
            field=models.CharField(max_length=20),
        ),
    ]
